#!/usr/bin/bash

#install the right packages, default yes to all
apt-get install puppet git -y

#Temporary until I implement through puppet; create and clone home directory
git clone https://github.com/Claem/home-directory.git /temp
mv ~/temp/.* ~
rm -rf ~/temp

#clear the default puppet repo and clone mine into into it
rm -rf /etc/puppet
git clone https://github.com/Claem/personal-puppet.git
#make a directory and clone puppet repo into it

#Run puppet
puppet apply /etc/puppet/manifests/site.pp

#Instructions for running::
1)vim bootstrap and copy this file in
2)sudo bash ./bootstrap
